### ISSUE TITLE
 jdk7-openjdk: Not working on ARMv5

### ISSUE THREAD

**Issue by Decade** [archlinuxarm/PKGBUILDs#1024]
Package: jdk7-openjdk-7.u71_2.5.3-1
Architecture: armv5
Device: PogoPlug E01 (Marvell Kirkwood) running linux-kirkwood kernel

What it isn't doing: I try to run any Java thing, and the JVM crashes with unhandled signal 4. Looking at the stack dump, I'm guessing the problem is currently somewhere in the class loader or the zipfile reader. It's extremely difficult for me to try compiling OpenJDK when OpenJDK requires a working javac to compile. :rage: And Oracle is not providing a JDK that runs _on_ an ARMv5.

What it should be doing: Java was working around the beginning of September, if I replaced ZeroVM with JamVM. But some update broke things, so JamVM doesn't work anymore, either. I wasn't watching closely, so I'm not sure which update.

Steps to reproduce: I guess you could try installing the latest version of OpenJDK on a Kirkwood device and seeing if you can run `javac`, no source documents needed.

**Comment by mpadilla2** [comment]
See the bug response from icedtea: http://icedtea.classpath.org/bugzilla/show_bug.cgi?id=2153

**Comment by kmihelich** [comment]
Try these packages, a quick check seems to show them working:
http://archlinuxarm.org/builder/testing/java/

**Comment by Decade** [comment]
Yes, a quick check seems to show them working on mine, too.

**Comment by kmihelich** [comment]
Packages are in the repos now.

**Comment by mpadilla2** [comment]
Everything is working great with the new packages. Thank you.
