### ISSUE TITLE
uboot-sunxi: No second CPU core

### ISSUE THREAD

**Issue by KenMacD** [archlinuxarm/PKGBUILDs#1027]
Package: `uboot-sunxi`
Architecture: `armv7`
Device: `cubieboard2`

Using the latest package, `cat /proc/cpuinfo`:

```
processor       : 0
model name      : ARMv7 Processor rev 4 (v7l)
Features        : half thumb fastmult vfp edsp thumbee neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 4

Hardware        : Allwinner sun7i (A20) Family
Revision        : 0000
Serial          : 0000000000000000
```

Flashing a newer u-boot gives:

```
processor       : 0
model name      : ARMv7 Processor rev 4 (v7l)
Features        : half thumb fastmult vfp edsp thumbee neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 4

processor       : 1
model name      : ARMv7 Processor rev 4 (v7l)
Features        : half thumb fastmult vfp edsp thumbee neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 4

Hardware        : Allwinner sun7i (A20) Family
Revision        : 0000
Serial          : 0000000000000000
```

**Comment by kmihelich** [comment]
Here are some packages to test with for cubieboard2 and cubietruck:
http://archlinuxarm.org/builder/testing/uboot-cubieboard2-2015.01-0-armv7h.pkg.tar.xz
http://archlinuxarm.org/builder/testing/uboot-cubietruck-2015.01-0-armv7h.pkg.tar.xz

The official package will be updated when 2015.01 is final; these are based on rc4.  There is no more uEnv.txt, a boot.scr is used instead.  This should boot a rootfs automatically from mmc, usb, or sata, and mounts root using PARTUUID (both MBR and GPT partitioning are fine).  You need to be on at least linux-sun7i 3.4.103-3 for this to work on the legacy kernel, as 3.4 required backports for that functionality.  I've flipped back and forth between that and linux-armv7 on the cubieboard2 and things seem to be working correctly.

In /boot, boot.txt has the plain-text version of boot.scr, and the mkscr script will run the mkimage command to create a boot.scr from that if you want to add to the bootargs, for example.

**Comment by CReimer** [comment]
Tried both linux-sun7i and linux-armv7. Both are booting fine.
Thanks

**Comment by freegigi** [comment]
I tried to run mainline kernel on a cubieboard2. After a clean install and full upgrade, I rebooted, then installed linux-armv7 and uboot-cubieboard2-2015.01-0-armv7h.pkg.tar.xz from above link. The board doesn't boot. Using a TTL cable I get this: http://pastebin.com/raw.php?i=NecE8AgU.

**Comment by WarheadsSE** [comment]
Perhaps examine the error?
```
Wrong image format for "source" command
```

**Comment by freegigi** [comment]
I saw that error, but I have no idea how to fix it. As far as I understand, the problem is in /boot/boot.scr and it was generated from boot.txt. However boot.txt is incomprehensible to me. Probably I need to do some reading on uboot. Too bad the wiki doesn't have anything.

**Comment by kmihelich** [comment]
Use the forum for your personal problems, not our issue tracker.

**Comment by CReimer** [comment]
Still no problems on my Cubieboard2. Both kernels are booting without any problem.
