### ISSUE TITLE
Cower: needs rebuild

### ISSUE THREAD

**Issue by aereaux** [archlinuxarm/PKGBUILDs#1054]
Package: cower
Architecure: armv7, but probably affects all.
Device: Samsung Galaxy S III

What it isn't doing: Running gives an error that it couldn't load alpm.

What it should be doing: Running and not giving that error.

Steps to reproduce: Run cower with an up-to-date pacman.

I think cower needs to be rebuilt, that's what fixed this same issue on my 64 bit installation.

**Comment by kmihelich** [comment]
Fixed.
