### ISSUE TITLE
community/xbmc: ERROR: Unable to create GUI. Exiting

### ISSUE THREAD

**Issue by qjcg** [archlinuxarm/PKGBUILDs#1061]
Package: **xbmc (13.2-6)**
Architecture: **armv7**
Device: **Odroid XU3 Lite**

*What it isn't doing:*
Executing `xbmc` without crashing.

*What it should be doing:*
Executing `xbmc` without crashing.

*Steps to reproduce:*
Run the `xbmc` command with no arguments.

[xbmc cli error output](https://gist.github.com/qjcg/462175ca0bc1ef8baa77#file-xbmc-cli-error-output)
[xbmc_crashlog-20150110_182631.log](https://gist.github.com/qjcg/462175ca0bc1ef8baa77#file-xbmc_crashlog-20150110_182631-log)

**Comment by qjcg** [comment]
What am I missing?

**Comment by WarheadsSE** [comment]
The log clearly states the failure. Read it.
