### ISSUE TITLE
Patch for kernel

### ISSUE THREAD

**Issue by zpon** [archlinuxarm/PKGBUILDs#1068]
I wanted to ask what your policy is with regards to patches of the kernel?
The reason I ask is that I use a DVB-C device which requires the patch from https://bugzilla.kernel.org/show_bug.cgi?id=72891. I have successfully compiled the kernel with the patch, and it is working fine, but it would be great if I could avoid compiling the kernel myself :).

BTW, the patch has been added to 3.19-rc5.

**Comment by kmihelich** [comment]
Start with the policy for this issue tracker.
https://github.com/archlinuxarm/PKGBUILDs/blob/master/CONTRIBUTING.md
