### ISSUE TITLE
LIRC sync problem

### ISSUE THREAD

**Issue by aplund** [archlinuxarm/PKGBUILDs#1093]
For those using the lirc codec there is a problem with the kernel where it doesn't send sync signals when it should to the lirc daemon.

I'm using the linux-imx6-cubox-dt package and this bug is in there as it's on a 3.14 kernel.

Can you please consider adding this patch to fix this problem?

https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=a8f29e89f2b54fbf2c52be341f149bc195b63a8b

**Comment by moonman** [comment]
People have to start following the guidlines or it will be marked as INVALID: https://github.com/archlinuxarm/PKGBUILDs/blob/master/CONTRIBUTING.md

Patch applied.
