### ISSUE TITLE
package-name: alarm/chromium-pepper-flash

### ISSUE THREAD

**Issue by Poincare1** [archlinuxarm/PKGBUILDs#1100]
Package: chromium-pepper-flash
Architecture: armv7
Device: odroid-xu3

What it isn't doing: Reflecting the current version of libpepflashplayer.so which is 16.0.0.305.

What it should be doing: Be up-to-date.

Steps to reproduce: installing current from this pkgbuild installs an old version and not the new version. You can reproduce this by installing chromium=pepper-flash as seeing it is an old version of libpepflashplayer.so.

**Comment by kmihelich** [comment]
Stop.
