### ISSUE TITLE
fbdev 0.4.4-4: driver not loading

### ISSUE THREAD

**Issue by pjaneck** [archlinuxarm/PKGBUILDs#1107]
Package: fbdev 0.4.4-4
Architecture: armv7h
Device: Samsung Chromebook XE303C12

What it isn't doing: loading the driver
dmesg gives: 
[drm:exynos_drm_gem_dumb_create] *ERROR* contig buffer allocation not supported
I don't know if this message is related.
When trying to start the xserver manualy with startx the log says:
Fatal server error: AddScreen/ScreenInit failed for driver 0

What it should be doing: loading the driver

Steps to reproduce: just install fbdev 0.4.4-4 and xorg-server 1.17.1-1 and reboot

**Comment by kmihelich** [comment]
No such package fbdev.  Usage issues belong in the forum.
