### ISSUE TITLE
Kodi-rbp: Alsa disabled

### ISSUE THREAD

**Issue by leonardder** [archlinuxarm/PKGBUILDs#1114]
Package: Kodi-RBP
Architecture: ARMV7H
Device: Raspberry Pi 2

What it isn't doing:
Kodi-rbp has alsa explicitly disabled. Therefore, external USB soundcards aren't supported by Kodi.

What it should be doing:
Alsa should be enabled --enable-alsa to support alsa output for external soundcards.

Steps to reproduce:
Go to settings, system and try to select an audio output. However an external soundcard is attached to the device, Kodi doesn't detect it because alsa support isn't built in.

**Comment by kmihelich** [comment]
Why is this not a pull request?

**Comment by leonardder** [comment]
Because I'm a blind user and Githubs pull request system is somehwat accessible. I however added two commits to http://github.com/leonardder/PKGBUILDs master branch, one for kodi-rbp and another for kodi-rbp-git to keep them in sync.

**Comment by jolan** [comment]
I just did PR#1116 before seeing this.  I only did stable since that's all I've tested so far.
