### ISSUE TITLE
Kodi-rbp: Keyboard letters not recognized

### ISSUE THREAD

**Issue by leonardder** [archlinuxarm/PKGBUILDs#1115]
Package: Kodi-RBP
Architecture: ARMV7H
Device: Raspberry Pi 2

What it isn't doing:
I have an external keyboard attached to my Banana Pi to operate Kodi. It is currently not possible to use the letter keys on the keyboard to navigate in lists or input in fileds (such as device name). However, pressing the p key for play works just fine.

What it should be doing:
Inputting letters in input fields and with quick navigation in lists should work correctly.

Steps to reproduce:
1. Go to settings>services>general>device name. It is currently not possible to input a new name there
2. Open a folder in the music library and try to navigate using shift+letter keys, i.e. shift+c to move to the classical music folder. Quick navigation doesn't work.

I've tested this on OpenElec with exactly the same settings, and it works as expected there.

**Comment by kmihelich** [comment]
Unsupported device.

**Comment by leonardder** [comment]
Hmm, ok. Could you please give a more detailed reason? What device is unsupported? Why should something that works on another OS be unsuported in this package?

**Comment by kmihelich** [comment]
> I have an external keyboard attached to my Banana Pi to operate Kodi.

**Comment by leonardder** [comment]
Ah, should have double checked my message. Fixed the initial post accordingly, the device in question is a Raspberry Pi 2.

**Comment by dhead666** [comment]
Try chmod /dev/tty0 to 0777

**Comment by kmihelich** [comment]
In that case, usage issues belong in the forum.  Still invalid.
