### ISSUE TITLE
xf86-video-fbturbo-git: no longer works as it should on sunxi devices

### ISSUE THREAD

**Issue by vonfritz** [archlinuxarm/PKGBUILDs#1117]
Package: xf86-video-fbturbo-git 
Architecture: armv7 
Device: sunxi

What it isn't doing:
see log:
[    15.117] (II) FBTURBO(0): no 3D acceleration because the driver has been compiled without libUMP
[    15.117] (II) FBTURBO(0): if this is wrong and needs to be fixed, please check ./configure log
[    15.118] (==) RandR enabled
[    15.297] (II) AIGLX: Screen 0 is not DRI2 capable
[    15.297] (EE) AIGLX: reverting to software rendering

What it should be doing:
see log:
[    16.156] (II) FBTURBO(0): enabled display controller hardware overlays for DRI2
[    16.156] (II) FBTURBO(0): Wait on SwapBuffers? enabled
[    16.156] (II) FBTURBO(0): [DRI2] Setup complete
[    16.156] (II) FBTURBO(0): [DRI2]   DRI driver: lima
[    16.156] (II) FBTURBO(0): [DRI2]   VDPAU driver: sunxi
[    16.156] (II) FBTURBO(0): using DRI2 integration for Mali GPU (UMP buffers)
[    16.156] (II) FBTURBO(0): Mali binary drivers can only accelerate EGL/GLES

revert https://github.com/archlinuxarm/PKGBUILDs/commit/0ba00d2ba66de78d5f03840626b89316a2ccea1b

ciao

**Comment by kmihelich** [comment]
The libump package no longer built, and we package no other libraries for sunxi.
