### ISSUE TITLE
linux-raspberrypi: mkknlimg fails checksum

### ISSUE THREAD

**Issue by PLyttle** [archlinuxarm/PKGBUILDs#1118]
Package: linux-raspberrypi
Architecture: ARMv5 /v7
Device: raspberrypi

What it isn't doing: 
Run makepkg without issues

What it should be doing: 
The download: https://github.com/raspberrypi/tools/raw/master/mkimage/mkknlimg fails the checksum. PKGBUILD lists '405015cdeb544575c25018b3487a2e76' while md5sum produces '69d50a4604a587ae770e4be244e293bd' . 
Probably missed an update? 

Steps to reproduce: 
should be obvious, type makepkg...

**Comment by kmihelich** [comment]
So update it, it'll probably get corrected on the next update. This really is an incredibly minor issue to waste time with an issue on.
