### ISSUE TITLE
Modules CONFIG_I2C_BCM2835 and CONFIG_SPI_BCM2835 are missing on RPI 2

### ISSUE THREAD

**Issue by blueperil** [archlinuxarm/PKGBUILDs#1120]
Package: linux-raspberrypi
Architecture: armv7h
Device: Raspberry Pi 2

What it isn't doing:
Modules CONFIG_I2C_BCM2835 and CONFIG_SPI_BCM2835 are missing

What it should be doing:

Steps to reproduce:
> zgrep BCM2835 /proc/config.gz
> \# CONFIG_I2C_BCM2835 is not set
> \# CONFIG_SPI_BCM2835 is not set

**Comment by kmihelich** [comment]
..so? What is the problem?

**Comment by blueperil** [comment]
Please enable the modules otherwise you can't use (some) extension cards on RPi2

**Comment by kmihelich** [comment]
These are not enabled in the v7 config from the RPi Foundation, therefore unlikely to be needed. Stop being vague, state an issue concisely.
