### ISSUE TITLE
php-apache: conflict with apache due to threading

### ISSUE THREAD

**Issue by zefie** [archlinuxarm/PKGBUILDs#1122]
Package: php-apache
Architecture: armv7h
Device: Raspberry Pi 2 B

What it isn't doing:
Allowing apache to start

What it should be doing:
Allowing apache to parse PHP

What it is doing:
[Tue Mar 03 03:18:30.275785 2015] [:crit] [pid 25954:tid 1993183232] Apache is running a threaded MPM, but your PHP Module is not compiled to be threadsafe.  You need to recompile PHP.
AH00013: Pre-configuration failed

Steps to reproduce:
pacman -S apache php-apache, enable the module

**Comment by kmihelich** [comment]
Usage issues belong in the forum.
