### ISSUE TITLE
gqrx: rebuild for newer boost

### ISSUE THREAD

**Issue by ajorg** [archlinuxarm/PKGBUILDs#1125]
Package: gqrx-2.3.0-1-armv6h
Architecture: armv6h
Device: Raspberry Pi B+

[andrew@alarmpi ~]$ gqrx
gqrx: error while loading shared libraries: libboost_system.so.1.55.0: cannot open shared object file: No such file or directory
[andrew@alarmpi ~]$ ls /usr/lib/libboost_system.so.1.*    
/usr/lib/libboost_system.so.1.57.0

Boost likes to change a lot, so packages that use it need to be rebuilt when it changes. Please rebuild.

**Comment by kmihelich** [comment]
Fixed.
