### ISSUE TITLE
foomatic-db: Non-ppd-file in directory foomatic-db-ppds

### ISSUE THREAD

**Issue by LinuCC** [archlinuxarm/PKGBUILDs#1126]
Package: foomatic-db-3:20141230-1
Architecture: ARMv7
Device: Raspberry Pi 2

What it isn't doing:
The file ```/usr/share/cups/model/foomatic-db-ppds/Kyocera/ReadMe.htm``` should not be there.
Cups seems to depend on the directory only containing ppds.
Cups errors with ```Bad driver information file "/usr/share/cups/model/foomatic-db-ppds/Kyocera/ReadMe.htm"!``` .
For the same issue on a different architecture, see the [Redhat Bugtracker](https://bugzilla.redhat.com/show_bug.cgi?id=514242).

What it should be doing:
The file should not be there so cups can do its cups-related things :)

Steps to reproduce:
Install ```foomatic-db```

**Comment by kmihelich** [comment]
We don't change this package. Confirm the issue on x86 Arch and file a bug in their tracker.
