### ISSUE TITLE
xorg-server: Segfault on mouse move

### ISSUE THREAD

**Issue by x11tete11x** [archlinuxarm/PKGBUILDs#1128]
Package: xorg-server (i think)
Architecture: armv6h
Device: Raspberry Pi B+

What it isn't doing: Xorg segfault when i move the mouse (Microsoft Wireless Optical Desktop 1000)

What it should be doing: Should works when i move the mouse

Steps to reproduce:
1) startx (in my case LXDE starts)
2) move the mouse (you will se an Xorg crash by a segfault)

logs and more info: http://archlinuxarm.org/forum/viewtopic.php?f=59&t=8583

**Comment by kmihelich** [comment]
"I think" is not a valid qualification.  When you have identified a specific bug in a specific package, let us know.

**Comment by x11tete11x** [comment]
:S but how i know what it's exactly wrong? there is a bug in somewhere.. i cant tell you if it's exactly on this package, or in udev or what..
