### ISSUE TITLE
rpb-kodi: included systemd service does not allow kodi user to restart or shutdown

### ISSUE THREAD

**Issue by graysky2** [archlinuxarm/PKGBUILDs#1139]
Package: rpb-kodi
Architecture: both armv6 and armv7
Device: RPi and RPi2

What it isn't doing: Interacting with systemd to allow Kodi to control system restart or shutdown.

What it should be doing: Allowing the system to restart or to shutdown from the Kodi GUI.

Steps to reproduce:
1) Install this package on RPi or RPi2
2) Start the kodi service
3) Try to restart or shutdown from the Kodi GUI (arrow down to the power button icon and hit ENTER)

**Comment by WarheadsSE** [comment]
Is this a problem somehow in the PKGBUILD?

**Comment by kmihelich** [comment]
No package with that name.
