### ISSUE TITLE
openssh: Failing to Start

### ISSUE THREAD

**Issue by daryltucker** [archlinuxarm/PKGBUILDs#1150]
Package: openssh 6.8p1-2
Architecture: ARMv7l Cortex-A7
Device: Raspberry Pi 2 B

### What it isn't doing:

`sshd` cannot start.

    systemctl --failed
    sshd.service   loaded  failed  failed  OpenSSH Daemon

### What it should be doing:

`sshd` should be able to start.

### Steps to reproduce:

1. Install via [Official Documentation](http://archlinuxarm.org/platforms/armv7/broadcom/raspberry-pi-2)
1. Turn on device.

### What I've tried:

1. Updated the System
  * `pacman -Syu`
1. Removed Package Cache and Re-Installed `openssh`
  * `pacman -Scc && pacman -S openssh`
1. Restarted `sshd.service`
  * `systemctl restart sshd.service`
1. Restarted (forcing fsck)
  * `shutdown -rF now`

**Comment by kmihelich** [comment]
Can't reproduce, package is working fine. Use the forum for usage issues.
