### ISSUE TITLE
openssh: Failing to Start

### ISSUE THREAD

**Issue by daryltucker** [archlinuxarm/PKGBUILDs#1151]
Package: openssh 6.8p1-2
Architecture: ARMv7l Cortex-A7
Device: Raspberry Pi 2 B

### What it isn't doing:

`sshd` cannot start.

    systemctl --failed
    sshd.service   loaded  failed  failed  OpenSSH Daemon

### What it should be doing:

`sshd` should be able to start.

### Steps to reproduce:

1. Install via [Official Documentation](http://archlinuxarm.org/platforms/armv7/broadcom/raspberry-pi-2)
1. Turn on device.

### What Fixed the Issue:

`openssh` installation on ArchLinux and other distributions has openssh generate certificates/keys on installation.  Upon further investigation, I discovered that the RSA key generated is not of a valid format and needs to be re-generated by the user:

1. `ssh-keygen -f /etc/ssh/ssh_host_rsa_key -N '' -t rsa -b 4096`
  * Select 'y' to overwrite the corrupted RSA key

I will do another installation of ArchLinux to see if I can reproduce the issue.

In the future, if you could leave tickets open to the person who opened it to provide feedback or additional information, that would be greatly appreciated.  There is nothing more frustrating than trying to contribute and being dealt with hastily.

**Comment by kmihelich** [comment]
Usage issues belong in the forum.  Do *not* open additional issues after they have closed.
