### ISSUE TITLE
New plex media server version

### ISSUE THREAD

**Issue by marlemion** [archlinuxarm/PKGBUILDs#1154]
There is a new plex media server version out:

https://downloads.plex.tv/plex-media-server/0.9.11.16.958-80f1748/PlexMediaServer-0.9.11.16.958-80f1748-arm.spk

It would be sweet to have the respective AUR PKBUILD updated. Thanks for all your great work. My NSA310 happily runs a recent kernel and a fully fledged arch right now. :)

**Comment by moonman** [comment]
Working on it. There are a couple of things left to iron out.
