### ISSUE TITLE
plexmediaserver problematic startup procedure

### ISSUE THREAD

**Issue by marlemion** [archlinuxarm/PKGBUILDs#1158]
Hi, thanks for pushing the new version of plex. However, the start script is problematic.

First, it does not include /etc/conf.d/plexmediaserver anymore. This is problematic, as some users might change the default values. E.g. in my setup, the server does not run as ple but another user. I allow only one plugin at the time and my application dir is at a different location. This cannot be achieved with the new script anymore and changes will get lost with the next update. So it is a design problem.

Second, not everyone uses or wants to use the given locales. E.g. on my system the plexmediaserver refused to start.

Third the SCRIPT variables are not clear to me.

With the following script, plexmediaserver starts happily and respects settings in /etc/conf.d/plexmediaserver

```
#!/bin/sh

# defaults - change these parameters in /etc/conf.d/plexmediaserver
export PLEX_MEDIA_SERVER_USER=plex
export PLEX_MEDIA_SERVER_MAX_PLUGIN_PROCS=6
export PLEX_MEDIA_SERVER_HOME=/opt/plexmediaserver
export PLEX_MEDIA_SERVER_MAX_STACK_SIZE=3000
export PLEX_MEDIA_SERVER_TMPDIR=/tmp
export PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR="${PLEX_MEDIA_SERVER_HOME}/Library/Application Support"

test -f /etc/conf.d/plexmediaserver && . /etc/conf.d/plexmediaserver

export LD_LIBRARY_PATH="${PLEX_MEDIA_SERVER_HOME}"
export TMPDIR="${PLEX_MEDIA_SERVER_TMPDIR}"

ulimit -s $PLEX_MEDIA_SERVER_MAX_STACK_SIZE

cd ${PLEX_MEDIA_SERVER_HOME}; su -c "${PLEX_MEDIA_SERVER_HOME}/Plex\ Media\ Server &" ${PLEX_MEDIA_SERVER_USER}
```

**Comment by moonman** [comment]
The package is from AUR, modified for arm. I would bring it up with AUR maintainer. Also do read rules for contributing.
