### ISSUE TITLE
kirkwood-dt 4.0-1 on r8619 network unusable

### ISSUE THREAD

**Issue by marlemion** [archlinuxarm/PKGBUILDs#1159]
Hi, thanks for pushing the new kernel version. However, the network driver r8619 seems to be problematic. My current setup: NSA310, stock u-boot, kernel 3.19 dt with appended dts file (nsa310a). It runs very nicely.
```
dmesg | grep r8
[    1.322210] r8169 Gigabit Ethernet driver 2.3LK-NAPI loaded
[    1.334381] r8169 0000:01:00.0 eth0: RTL8168d/8111d at 0xd096c000, fc:f5:28:76:b4:e5, XID 083000c0 IRQ 83
[    1.344032] r8169 0000:01:00.0 eth0: jumbo features [frames: 9200 bytes, tx checksumming: ko]
[    1.565371] usbcore: registered new interface driver r8712u
[    8.214197] r8169 0000:01:00.0 enp1s0: renamed from eth0
```

When I upgraded to 4.0-1, the network does not come up (yellow led blinking instead of green) and the console is flooded with:

```
r8169: rtl_phyar_cond == 1 (loop: 20, delay: 25). 
```

dmesg output is the same as for the 3.19 kernel. For now, I reverted back to 3.19 and everything works out of the box again.

Tested with both dhcpcd and systemd-networkd. If neither of them is loaded, the console is not flooded with the messages.

**Comment by kmihelich** [comment]
https://github.com/archlinuxarm/PKGBUILDs/blob/master/CONTRIBUTING.md
