### ISSUE TITLE
CLISP: segfaults on loading "quicklisp.lisp"

### ISSUE THREAD

**Issue by namandixit** [archlinuxarm/PKGBUILDs#1170]
On CLISP v2.49 on Arch Linux (armv7h) running in an chroot on Android 4.4.4 (kernel 3.4.105) with Mediatek MT6582 chip, loading quickilisp.lisp (downloaded from official sources) results in a Segmentation Fault. 
![screenshot_2015-04-24-20-53-32](https://cloud.githubusercontent.com/assets/8736472/7322780/f00e2c28-eac7-11e4-82fe-c4f51f5f7d83.png)

This behaviour is only shown for this particular file (insofar as I am aware) and only with CLISP (ECL works fine).

**Comment by WarheadsSE** [comment]
https://github.com/archlinuxarm/PKGBUILDs/blob/master/CONTRIBUTING.md
