### ISSUE TITLE
systemd 219-6: eth0 not comming up on boot

### ISSUE THREAD

**Issue by xfjx** [archlinuxarm/PKGBUILDs#1173]
Package: systemd
Architecture: armv7l
Device: odroid-u3

What it isn't doing:
eth0 not comming up on boot. ifconfig only shows loopback

What it should be doing:
starting up eth0

Steps to reproduce:
upgrade systemd to 219-6 and reboot the system

Fix:
backport to 218-2 worked for me

**Comment by kmihelich** [comment]
Can't reproduce.
