### ISSUE TITLE
package-name: kodi-rbp 

### ISSUE THREAD

**Issue by ottuzzi** [archlinuxarm/PKGBUILDs#1179]
Package: kodi-rbp 
Architecture: armv7 
Device: rbp2

What it isn't doing: does not play videos. Some videos are played as music files, some do not play at all and the system becomes unresponsive. 

What it should be doing: it should play videos. Music files are played correctly 

Steps to reproduce: rbp2 updated Tuesday night UTC with pacman - Syu 

Please see #1178 for a more descriptive version. 

Thanks in advance 
Bye 
Piero

**Comment by kmihelich** [comment]
Insufficient information to debug.  Use the forum for usage issues.
