### ISSUE TITLE
linux-odroid-c1: Build failed

### ISSUE THREAD

**Issue by bugthing** [archlinuxarm/PKGBUILDs#1184]
Package: linux-odroid-c1
Architecture: armv7
Device: odroid-c1

What it isn't doing: Building the package
It fails with the following error:
  ==> ERROR: Build failed, check /home/bugthing/chroot/bugthing/build

What it should be doing: Building package ready for install

Steps to reproduce:

Fresh install of Arch on ODroidC1 as per - http://archlinuxarm.org/platforms/armv7/amlogic/odroid-c1

**As root**
  $ pacman -Syyuu
  $ pacman -S git base-devel devtools-alarm
  $ useradd -m -g users -G wheel -s /bin/bash bugthing
  $ passwd bugthing
  $ visudo # <- enable wheel as sudo group
  $ pacman-key --init # <- because: "cp: cannot stat '/etc/pacman.d/gnupg': No such file or directory"

**As user (bugthing)**
  $ git clone https://github.com/archlinuxarm/PKGBUILDs.git
  $ cd PKGBUILDs/core/linux-odroid-c1/
  $ vi PKGBUILD # <- change plgrel to "1.1" and uncomment "make nconfig"
  $ CHROOT=$HOME/chroot
  $ mkdir $CHROOT
  $ mkarchroot $CHROOT/root base-devel
  $ arch-nspawn $CHROOT/root pacman -Syu
  $ makechrootpkg -c -r $CHROOT

==> Creating clean working copy [bugthing]...done
==> Making package: linux-odroid-c1 3.10.75-1.1 (Mon May 11 21:16:41 UTC 2015)
==> Retrieving sources...
  -> Found a7614398199a077cdfe1e4ba821510c05ca847ce.tar.gz
  -> Updating c1_bootini git repo...
Fetching origin
  -> Found config
  -> Found amlogic.service
  -> Found 0001-dirty-status-led-active-low-hack.patch
  -> Found 0002-remove-backports-cflags.patch
==> Validating source files with md5sums...
    a7614398199a077cdfe1e4ba821510c05ca847ce.tar.gz ... Passed
    c1_bootini ... Skipped
    config ... Passed
    amlogic.service ... Passed
    0001-dirty-status-led-active-low-hack.patch ... Passed
    0002-remove-backports-cflags.patch ... Passed
==> ERROR: Build failed, check /home/bugthing/chroot/bugthing/build

  $ find /home/bugthing/chroot/bugthing/build
/home/bugthing/chroot/bugthing/build

**Comment by kmihelich** [comment]
Usage issues belong in the forum.
