### ISSUE TITLE
plex-media-server: New version available on the AUR

### ISSUE THREAD

**Issue by tokenize47** [archlinuxarm/PKGBUILDs#1185]
Package: plex-media-server
Architecture: armv5 and armv7
Device: RaspberryPi 2

What it isn't doing: Everything is fine, this is just an update request.

What it should be doing: Everything is fine, this is just an update request.

Steps to reproduce: N/A

**Comment by moonman** [comment]
@tokenize47 Just send me a PM on forum next time if I haven't updated the package. I don't check this package for updates every day. ;)
