### ISSUE TITLE
Fsck caveats

### ISSUE THREAD

**Issue by postblue** [archlinuxarm/PKGBUILDs#1196]
The distribution is a hell to maintain unbroken. I love Arch Linux, but I would like (please) to be able to `fsck` automatically on boot every time a dirty bit is found. But I find no way to do so.

As [the documentation](https://wiki.archlinux.org/index.php/Fsck#Boot_time_checking) states, there are few solutions:
* fsck the root filesystem before mounting it via the `fsck` hook, but even if I install `mkinitcpio` (removed in #218), the default configuration is not working and any kind of documentation on how it should be working in Arch Linux ARM is nowhere to be found.
* fsck with systemd each filesystem having a fsck pass number greater than 0, but the default fstab is set to 0 (why) with only the /boot partition in it (why not / ?). Moreover, systemd needs the fsck'ed partitions to be mounted as read-only, but the root partition is mounted as `rw` in `/boot/cmdline.txt`.

Is it possible to implement a solution in Arch Linux ARM (having back mkinitcpio ?) so we could have a working fsck ?

Thank you. :)

**Comment by WarheadsSE** [comment]
Make an initramfs, and add it to your bootloader config. Have at.
