### ISSUE TITLE
linux-armv7: Realtek RTL8153 not supported

### ISSUE THREAD

**Issue by PythonNut** [archlinuxarm/PKGBUILDs#1197]
Package: `linux-armv7`
Architecture: `armv7`
Device: `Raspberry Pi 2 Model B`

**What it isn't doing:**
The Realtek RTL8153 is the chip inside a whole slew of USB3.0 to 3xUSB3.0 + GigE adapters, like this one (which I own):

![Image](http://ecx.images-amazon.com/images/I/51RUwnie4bL._SX425_.jpg)

Arch Linux ARM correctly detects the USB hub, but fails to detect the Ethernet port. `ifconfig` does not show the interface.

**What it should be doing:**

`ifconfig` should show a new interface (probably `eth1`). Note that **Raspbian does not have this problem**, which is why I'm reporting this here, and not on the raspberrypi linux/firmware trackers.

**Steps to reproduce:**
1. Plug device with Realtek RTL8153 chipset into USB port.
2. Note that `ifconfig` does not register a new network interface.

**Comment by kmihelich** [comment]
The required module is built with that kernel.  Use the forum for usage issues.
