### ISSUE TITLE
Add Banana Pi/Banana Pro

### ISSUE THREAD

**Issue by seidler2547** [archlinuxarm/PKGBUILDs#1205]
Is it possible to add the Banana Pi/Pro? As far as I can see, only uboot needs to add another package definition. Since it is almost identical to the Cubieboard2 and supported upstream (and also, for example, by Debian), it should only be a technicality.

Iʼm receiving a Banana Pi some time soon, so Iʼm happy to test.

**Comment by WarheadsSE** [comment]
This is forum/IRC, not an issue with packaging.
