### ISSUE TITLE
perl-datetime: Broken after core/perl upgrade to 5.22.0-1

### ISSUE THREAD

**Issue by PlanetEater** [archlinuxarm/PKGBUILDs#1212]
Package: perl-datetime-1.18-1
What it isn't doing:
package is broken after core/perl upgrade to 5.22.0-1
Steps to reproduce:
```
$ pacman -Ss perl-datetime$
community/perl-datetime 1.18-1 [installed]
    A complete, easy to use date and time object

$ perl -e "use DateTime;"
perl: symbol lookup error: /usr/lib/perl5/vendor_perl/auto/DateTime/DateTime.so: undefined symbol: Perl_xs_apiversion_bootcheck
```
Package should be rebuilt against the new version of core/perl.  Also,  a newer version of the package (1.19)  is available in the Arch repos:
https://www.archlinux.org/packages/community/x86_64/perl-datetime/

**Comment by kmihelich** [comment]
Fixed.
