### ISSUE TITLE
docker:bug in 1.7.0 on ARM

### ISSUE THREAD

**Issue by troyfontaine** [archlinuxarm/PKGBUILDs#1216]
Package: docker 1.7.0
Architecture: ARMv7h
Device: Raspberry Pi 2

What it isn't doing: Cannot build container images - "socket operation on non-socket" error - known issue in 1.7.0 of Docker as per https://github.com/docker/docker/issues/14184

What it should be doing: Container should build without error.  Is fixed in 1.7.1

Steps to reproduce: Attempt to build a container using Docker 1.7.0-you will receive this error.

**Comment by WarheadsSE** [comment]
Ah, wasn't aware it had been released, but yes I know.

**Comment by WarheadsSE** [comment]
once it is released, I will update it. It has not yet been tagged and released.

**Comment by pavel** [comment]
@WarheadsSE Iht would be great if you've could put docker's 1.7.1 latest rc, for example, as docker-rc aur package.

**Comment by GerardRibas** [comment]
@pavel did you solve the issue? I'm having the same problem as you

**Comment by WarheadsSE** [comment]
@GerardRibas the above issue @ docker/docker is sorted in 1.7.1-rc1 as that states. I will not however package that for the distribution.

**Comment by pavel** [comment]
@WarheadsSE Got the 1.7.1-rc3 thing build, but when doing `docker run hello-world` or building a container I get: `[8] System error: exec format error`.

@GerardRibas If you're interested here's the modified PKGBUILD for the 1.7.1-rc3:

**Comment by WarheadsSE** [comment]
Exec format errors are because you are attempting to run x86-64 containers

**Comment by troyfontaine** [comment]
@WarheadsSE Sorry, I submitted the ticket when I was already on auto-pilot at the keyboard and missed that the release wasn't ready.  I've downgraded Docker in the interim until they release the new version.  Thanks for the update!

**Comment by pavel** [comment]
@WarheadsSE My bad. Sure I can not run x86-64 containers on ARM CPU. Docker works fine.
