### ISSUE TITLE
kodi-rpi: framebuffer needs to be disabled

### ISSUE THREAD

**Issue by graysky2** [archlinuxarm/PKGBUILDs#1228]
Package: kodi-rbp
Architecture: kodi-rbp
Device: RPi2 outputting to an SDTV

What it isn't doing: The framebuffer is not getting killed before Kodi is launched.  This has the effect of allowing the dmesg output to be viable when viewing non-4:3 aspect ratio videos although the GUI is fine since it takes up the entire screen real-estate.

What it should be doing: Per the Kodi devs, the console framebuffer should be killer before launching Kodi[1].

1. http://forum.kodi.tv/showthread.php?tid=233956&pid=2074997#pid2074997
![partial](https://cloud.githubusercontent.com/assets/534822/9154909/1caac922-3e73-11e5-8ef7-b7a7ec00e804.jpg)

Steps to reproduce:
1) Launch kodi from the systemd service while connected to a SDTV via the video port (not HDMI) of the RPi2.
2) Play a video that has been cropped such as an anomorphic movie.

**Comment by gituser6** [comment]
Oh I am so glad someone else has this problem. This is just the same for me. How do we disable the framebuffer?
