### ISSUE TITLE
kodi-rbp: Restart loop when connecting MariaDB

### ISSUE THREAD

**Issue by Signupnow** [archlinuxarm/PKGBUILDs#1242]
Package: kodi-rbp-15.1-1
Architecture: armv6l(h)
Device: Raspberry Pi 1 version B

I am using the following advancedsettings.xml file to connect it, and I have no problem to run kodi without the file.
When the file is present kodi boots up but restart just before displaying the Movies / Music / Settings bar (I can see the splash screen then the backgound, then it restarts).
Nothing is useful in the [crashlog](https://gist.github.com/Signupnow/3602f93cdac9bb25e4bf)...

Reverting to kodi-rbp-15.0-2 is fixing my issue.

    <advancedsettings>
      <videodatabase>
        <type>mysql</type>
        <host>127.0.0.1</host>
        <port>3306</port>
        <user>kodi</user>
        <pass>kodi</pass>
      </videodatabase>
      <musicdatabase>
        <type>mysql</type>
        <host>127.0.0.1</host>
        <port>3306</port>
        <user>kodi</user>
        <pass>kodi</pass>
      </musicdatabase>
      <videolibrary>
        <importwatchedstate>true</importwatchedstate>
        <importresumepoint>true</importresumepoint>
      </videolibrary>
    </advancedsettings>

What it isn't doing: Connecting to MariaDB and show kodi GUI

What it should be doing: Kodi should connect MariaDB and shows GUI

Steps to reproduce: 
* Install the package
* Follow [Official Kodi wiki](http://kodi.wiki/view/MySQL/Setting_up_MySQL#tab=Arch_Linux) to install MariaDB
* Add the preceding [advancedsettings.xml](http://kodi.wiki/view/Advancedsettings.xml) in your [userdata](http://kodi.wiki/view/Userdata_folder) folder
* Launch kodi

Personnaly I use the kodi systemd service wich launches kodi-standalone (which is why it restarts I think, as Restart is set at "on-failure"), but I have tried lauching kodi as a standard user and it will have the same problem.

Is it just me? On Archlinux X86_64 it works well...

**Comment by wari** [comment]
Fails on mine too on this new update. Got a huge core file. I'm using kodi launching as a normal user, not kodi-standalone. It does not fail it I remove the mysql server settings, but when I add it back in, it dies. Same version of Kodi on Mac OS X with the same advanced-settings.xml file works normally.
