### ISSUE TITLE
systemd-timesyncd

### ISSUE THREAD

**Issue by vitalytarasov** [archlinuxarm/PKGBUILDs#1247]
Package: systemd-timesyncd
Architecture: all
Device: RPI2

What it isn't doing: writes periodically to /var/lib/systemd/clock which wears out SD card; this location is hard-coded, 

What it should be doing: location /var/lib/systemd/clock should be configurable

Steps to reproduce: ls -l /var/lib/systemd/clock

**Comment by moonman** [comment]
With Flash Translation Layer on the flash it is really not a big deal. If you still want it configurable then submit a bugreport with systemd developers, not us. We are not the ones behind systemd.
