### ISSUE TITLE
linux-peach: dd's bootloader over root partition

### ISSUE THREAD

**Issue by Veyrdite** [archlinuxarm/PKGBUILDs#1253]
Package: linux-peach
Architecture: armv7h
Device: Chromebook (snow)

**What it does:** during installation of the package it asks if it can install the vmlinux.kpart to a certain partition.  (In my case) this partition is incorrect.

**What it should be doing:**  Explaining clearly that it wants to dd the vmlinux.kpart to the start of the partition, and warn the user that this is VERY dangerous if the wrong partition was chosen, rather than just displaying a standard (Y/n) decision.

**Steps to reproduce:** I have not attempted to reproduce this!  I made some other mistakes during recovery that made the process difficult and I'm currently overseas with poor internet access. 

I have been running linux-snow for almost a couple of years (and have been holding back systemd packages because they require a newer kernel).  When I discovered that linux-snow is no longer in the repos but linux-peach is instead I installed it.  

A script (I presume?) during the package install process asked if it could write the new kernel image to /dev/mmcblk0p3.  This was my root partition (the installation instructions for snow chromebooks have now changed the partition layout) and I made the poor decision of agreeing.  All data on this partition was lost immediately.

**Comment by kmihelich** [comment]
linux-peach is not compatible with old installations using linux-chromebook.
