### ISSUE TITLE
odroid-c1-remote service fail to start

### ISSUE THREAD

**Issue by RyuzakiKK** [archlinuxarm/PKGBUILDs#1260]
Package: alarm/odroid-c1-remote
Architecture: armv7h
Device: ODROID-C1+

If you try to run
```
# systemctl start odroid_remote
```
will fail with the error: `Can't open /dev/amremote`

I think this is due to the switch to lirc http://forum.odroid.com/viewtopic.php?f=117&t=11991

**Comment by WarheadsSE** [comment]
This a problem stemming from the upstream source, and the default conf there-in
