### ISSUE TITLE
Pulseaudio support in kodi-rbp disabled?

### ISSUE THREAD

**Issue by Split7fire** [archlinuxarm/PKGBUILDs#1278]
Kodi-rbp pkgbuild has "--disable-pulse" in configuration section. Why?

**Comment by Split7fire** [comment]
Why this issue is marked as "Invalid"?

**Comment by moonman** [comment]
1. https://github.com/archlinuxarm/PKGBUILDs/blob/master/CONTRIBUTING.md
2. This is not an issue, but rather a question. See 1.
