### ISSUE TITLE
mkvtoolnix-cli: Can't execute mkvmerge

### ISSUE THREAD

**Issue by RubenSilveira** [archlinuxarm/PKGBUILDs#1286]
Package: mkvtoolnix-cli 8.5.0-1
Architecture: armv5
Device: QNAP TS-212

What it isn't doing: When I execute mkvmerge it errors out with "error while loading shared libraries: libboost_regex.so.1.58.0: cannot open shared object file: No such file or directory".

What it should be doing: Presently, boost-libs are already at version 1.59.0-2, so I would assume mkvtoolnix-cli only needs upgrading in order to fix this issue. Would the package maintainer please upgrade this package to 8.5.1-1 (or whatever more recent version is)?

Steps to reproduce: pacman -Suyy --noconfirm ; mkvmerge

**Comment by kmihelich** [comment]
Fixed 3 hours ago. Update your system *before* filing bugs.
