### ISSUE TITLE
libtirpc: Faulty authentication

### ISSUE THREAD

**Issue by MrksHfmn** [archlinuxarm/PKGBUILDs#1296]
Package: upgraded libtirpc (0.3.2-2 -> 1.0.1-2)
Architecture: armv7h
Device: ODROID C1

What it isn't doing: SSH, Login, etc.

What it should be doing: 

Steps to reproduce: Upgrading

 PAM unable to dlopen(/usr/lib/security/pam_unix.so): /usr/lib/libtirpc.so.1: undefined
symbol: __rpc_get_default_domain

**Comment by ingwinlu** [comment]
upstream bumped the packages, users that have not updated yet should wait for those packages to land in the repo.

For those with a broken installation symlinking acording to http://archlinuxarm.org/forum/viewtopic.php?f=57&t=9478 should result in an installation that is updateable.

**Comment by kmihelich** [comment]
Fixed.
