### ISSUE TITLE
core/linux-armv7 replacement for linux-wandboard breaks kodi-imx

### ISSUE THREAD

**Issue by jaarandaz** [archlinuxarm/PKGBUILDs#1304]
Package: core/linux-armv7
Architecture: armv7h
Device: wandboard quad

What it isn't doing: kodi-imx gives a segmentation fault

What it should be doing: work?

Steps to reproduce: 
1. install linux-armv7 and kodi-imx
2. run kodi-standalone

**Comment by kmihelich** [comment]
Not a bug.
