### ISSUE TITLE
docker -d error

### ISSUE THREAD

**Issue by argoneus** [archlinuxarm/PKGBUILDs#822]
I'm getting an error when running docker -d.  `pacman` says I have version `docker 1:0.10.0-1`

The error is https://gist.github.com/argoneus/c99e5ef889d51c10f2e4

I believe docker on alarm is missing some deltas to run on the ARM platform.  resin.io has a patch for ARM builds (https://github.com/resin-io/lxc-docker-PKGBUILD/blob/master/docker-arm-v0.8.0.patch) that modifies several files that aren't included in the alarm patch (https://github.com/archlinuxarm/PKGBUILDs/blob/master/community/docker/docker-arm.patch).

**Comment by djmaze** [comment]
@argoneus: Did you try Docker 1.5.0 already? Works like a charm for me (on different ARM devices, that is).

**Comment by WarheadsSE** [comment]
I still need to re-try with ARMv5 (pressing hard)

**Comment by argoneus** [comment]
I'll updated and try it soon, thanks for the reminder!

**Comment by argoneus** [comment]
I've installed docker 1.5.0 on ALARM and it works great, with no errors.  Apologies for the delay in testing this out; I had to rebuild Arch on my TP1.
