### ISSUE TITLE
intellij-idea-community-edition

### ISSUE THREAD

**Issue by ramiroblanco** [archlinuxarm/PKGBUILDs#831]
Package: intellij-idea-community-edition
Architecture: armv7
Device: odroid-xu

What it isn't doing: 
Open or save any files. it complains about files being too large. eg.: "java.io.IOException: File is too large: 597000454144, file:///home/odroid/IdeaProjects/untitled1/.idea/scopes/scope_settings.xml"

What it should be doing: 
Open files, save files.

Steps to reproduce: 
a) create empty project, open txt file (or any file, any size) throws: "File $file is too large for Intellij IDEA editor"
b) create empty project. close, open again and it will throw "Could not save project:
java.io.IOException: File is too large: 627065225216, file:///home/odroid/IdeaProjects/untitled2/.idea/modules.xml"

**Comment by kmihelich** [comment]
Fixed in 15.0.1.
