### ISSUE TITLE
sbcl now available for ARM

### ISSUE THREAD

**Issue by bchretien** [archlinuxarm/PKGBUILDs#881]
[sbcl](http://www.sbcl.org/news.html) (Common Lisp compiler currently available in [[extra]](https://www.archlinux.org/packages/?sort=&q=sbcl&maintainer=&flagged=)) now has ARM support since [version 1.2.0](http://www.sbcl.org/all-news.html#1.2.0). This was among problematic packages for ARM users who wanted to use ROS as reported in https://github.com/ros/roslisp/issues/14. I guess this could be a nice addition to the  other PKGBUILDs.

**Comment by kmihelich** [comment]
In repos soon for v7.
