### ISSUE TITLE
docker: 1.2.0 not recognizing btrfs filesystem

### ISSUE THREAD

**Issue by djmaze** [archlinuxarm/PKGBUILDs#963]
Package: docker
Architecture: armv7
Device: ODROID U3
 docker daemon: 1.2.0 fa7b24f-dirty; execdriver: native; graphdriver: btrfs

What it isn't doing: 

The docker daemon won't start anymore after the upgrade. Instead, the journal tells me:

    prerequisites for driver not satisfied (wrong filesystem?)

What it should be doing: 

The daemon should start successfully.

Steps to reproduce:

* Run docker 1.0.0 with a btrfs filesystem mounted at `/var/lib/docker`. (Need to add `-s btrfs` to the `ExecStart` line in _/usr/lib/systemd/system/docker.service_ beforehand.) 
* Upgrade docker to 1.2.0. 
* Re-add the `-s btrfs` flag to the _docker.service_ file.  
* `sudo systemctl daemon-reload && sudo systemctl restart docker`  

Thoughts:

I recognize the [btrfs detection patch has been removed during the upgrade to 1.2.0](https://github.com/archlinuxarm/PKGBUILDs/commit/f5a9cd5c82ac810836561fd9d05a580f36a140d4#diff-2). Maybe this is still needed?

**Comment by asssaf** [comment]
Is there a workaround?

**Comment by djmaze** [comment]
Did not yet have an opportunity to look at this again. Will get a new device in the coming days where I will try to get this working, hopefully making some progress.

**Comment by asssaf** [comment]
I've been testing this in QEMU so far.
If you'd like I test your work on my Pi.

**Comment by WarheadsSE** [comment]
This does really need updated too...

**Comment by djmaze** [comment]
Ok, so I just tried re-adding the `0002-Fix-btrfs-detection-on-ARM.patch` to the latest 1.4.1 PKGBUILD. I tested it on my new ODROID-C1. Btrfs is working fast and flawlessly as a storage driver. Moreover, it does not exhibit slow container deletion times, including errors in syslog, as I am experiencing with the default devicemapper driver. 

From my point of my view, btrfs seems to be the better choice. The compatibility patch really should be added back. I can make a PR if you wish.

**Comment by kmihelich** [comment]
Yes, please submit a PR if this has been fully tested.

**Comment by djmaze** [comment]
So, it seems as of 1.5.0, Docker [does not need patches anymore](https://github.com/archlinuxarm/PKGBUILDs/commit/285031f2389db5ce848f1cb7bb7b2e7368c2c465). Even btrfs works out of the box now. Which is great!

```
$ sudo docker info
Containers: 4
Images: 34
Storage Driver: btrfs
 Build Version: Btrfs v3.18.2
 Library Version: 101
Execution Driver: native-0.2
Kernel Version: 3.10.66-1-ARCH
Operating System: Arch Linux ARM
CPUs: 4
Total Memory: 846.2 MiB
[...]
```
